Repository leletheprogrammer/SA_Progetto, pull requests merged in 2022-09, with the labels that each got.

#84 Aggiungere maggiori dataset
  crud_tables_management.py
  main.py
  templates/datasets.html
  templates/home.html
Labels: enhancement

#90 Addestramento maggiori dataset
  bert_training.py
  dataset.py
  main.py
  preparation.py
  preprocessing.py
  templates/home.html
  templates/start_training_model.html
  templates/status.html
  templates/training_phrases.html
  training.py
  training_ee.py
Labels: enhancement

#94 Realizzata v. 1.8 dei documenti
  documentation/Documento_tecnico_NLPWebPlatform.docx
  documentation/Guida_uso_NLPWebPlatform.docx
Labels: documentation

#95 Download e cancellazione maggiori dataset
  download_erasure.py
  main.py
  templates/download_erasure_model.html
  training.py
Labels: enhancement

#100 Realizzata v. 2.0 dei documenti
  documentation/Documento_tecnico_NLPWebPlatform.docx
  documentation/Guida_uso_NLPWebPlatform.docx
Labels: documentation

#99 Problemi vari
  templates/dataset_results_testing.html
  templates/start_training_model.html
  templates/status.html
Labels: bug

#103 Aggiunta licenza e aggiornato README.md
  LICENSE.md
  README.md
Labels: documentation

#104 Completato definitivamente power point
  documentation/NLP Web Platform.pptx
Labels: documentation
